const properties=[
    { 
        name:'Alcove Studio',
        image:'https://i.ibb.co/sj6Jk0d/Alcove-Studio.webp',
        location:'Mirpur Dhaka' ,
         bed:5,
         bathroom:4,
         size:800 ,
         price:80000 ,
         quantity:1,
         dining:'https://i.ibb.co/1MJ6FTG/alcovestudiodining-2.jpg ',
         wash:'https://i.ibb.co/vLFfbwF/Alcove-Studiowash-3.jpg ',
         kitchen:'https://i.ibb.co/Y0M6Yrm/Alcove-Studiokitchen-4.jpg '
    },
    { 
        name:'Affordable Urban House',
        image:'https://i.ibb.co/JFBM7YP/Affordable-Urban-House.jpg',
        location:'Pathantula Sylhet' ,
        bed:3,
        bathroom:2,
        size:600,
         price:50000,
         quantity:1,
         dining:'https://i.ibb.co/x8v8Cp0/Affordable-Urban-2.jpg ',
         wash:'https://i.ibb.co/SmsWyc4/Affordable-Urban-Wash3.jpg ',
         kitchen:'https://i.ibb.co/S3Sg1Vh/Affordable-Urban-Kitchen4.jpg '
    },
    { 
        name:'Convertible Studio',
        image:'https://i.ibb.co/ZK6mJX1/Convertible-Studio.webp',
        location:'New Market' ,
         bed:4,
         bathroom:3,
         size:900 ,
         price:70000 ,
         quantity:1,
         dining:'https://i.ibb.co/GkJKWv3/convertible-Studio-Dining-2.jpg ',
         wash:'https://i.ibb.co/2sNq5ys/Convertible-Studiowash-3.jpg ',
         kitchen:'https://i.ibb.co/Vx8DM0F/convertiblestudiokitchen-4.jpg '
    },
    { 
        name:'Home In Metric Way',
        image:'https://i.ibb.co/TKZHG5Q/Home-In-Metric-Way.webp',
        location:'GulShan Dhaka' ,
         bed:4,
         bathroom:4,
         size:700 ,
         price:65000 ,
         quantity:1,
         dining:'https://i.ibb.co/SVsyBrD/Homeinmetric-Dining-2.jpg ',
         wash:'https://i.ibb.co/ScRvN3H/Homeinmetricwash3.jpg ',
         kitchen:'https://i.ibb.co/VSD143p/Home-In-Metric-Wkitchen-4.jpg '
    },
    { 
        name:'Micro Apartment',
        image:'https://i.ibb.co/tmv7C8s/Micro-Apartment.webp',
        location:'Uttara Dhaka',
         bed:2,
         bathroom:1,
         size:400,
         price:30000,
         quantity:1,
         dining:'https://i.ibb.co/vkx37F8/microapartment-Dining-2.jpg ',
         wash:'https://i.ibb.co/SNZsnm6/microapartmentwash-3.jpg ',
         kitchen:'https://i.ibb.co/SQ74hfL/Micro-APrtmentkitchen-4.jpg '
    },
    { 
        name:'Pent House',
        image:'https://i.ibb.co/J7Y5J2F/penthouse.jpg',
        location:'Muradpur Chittagong' ,
         bed:4,
         bathroom:3,
         size:820 ,
         price: 55000,
         quantity:1,
         dining:'https://i.ibb.co/BNGfv38/pent-House-Dining-2.jpg ',
         wash:'https://i.ibb.co/K64Z6GM/Penthousewash-3.jpg ',
         kitchen:'https://i.ibb.co/dJyDTxD/penthouse-Kitchen-4.jpg '
    },
    { 
        name:'Rail Road Apartment',
        image:'https://i.ibb.co/SDjPxnz/Rail-Road-Apartment.webp',
        location: 'Gowainghat Sylhet' ,
         bed:4,
         bathroom:4,
         size:700 ,
         price:64000 ,
         quantity:1,
         dining:'https://i.ibb.co/FDcCMHw/railroad-Apartmentdininng-2.jpg ',
         wash:'https://i.ibb.co/pKMtJtj/railroad-apartmentwash-3.jpg ',
         kitchen:'https://i.ibb.co/WHNrLwv/railroad-apartment-kitchen-4.jpg ',
        
    },
    { 
        name:'Walk Up',
        image:'https://i.ibb.co/B3vzx9p/Walk-Up.webp',
        location:'GEC Chittagong' ,
         bed:5,
         bathroom:4,
         size:950,
         price:99000 ,
         quantity:1,
         dining:'https://i.ibb.co/KmyhyLk/walkupdining-2.jpg ',
         wash:'https://i.ibb.co/xsp1vD1/walkwash-3.jpg ',
         kitchen:'https://i.ibb.co/r6NfbGC/walkupkitchen-4.jpg ',
         
    },
    { 
        name:'Park Avenue Apartment',
        image:'https://i.ibb.co/P9HdCS0/Park-Avenue-APartment.jpg',
        location:'Agradbad Chittagong' ,
         bed:4,
         bathroom:3,
         size:810,
         price:62000 ,
         quantity:1,
         dining:'https://i.ibb.co/v4Z71rd/park-Avenue-Dining-2.jpg ',
         wash:'https://i.ibb.co/D9VysHP/Park-Avenuewash-3-1.jpg ',
         kitchen:'https://i.ibb.co/Srr97wn/park-Avenue-Aprt-kit-4.jpg ',
        
    },
    { 
        name:'Diamond Manor Apartment',
        image:'https://i.ibb.co/h8XcMFn/Diamond-Manor-APrtent.jpg',
        location:'Mouchak Dhaka',
         bed:3,
         bathroom:3,
         size:650,
         price:67000,
         quantity:1,
         dining:'https://i.ibb.co/vhmtfg4/Diamond-Manor-APrte-Dining-2.jpg',
         wash:'https://i.ibb.co/TYv1rdh/Diamond-Manor-APrtewash-3.jpg ',
         kitchen:'https://i.ibb.co/nm4kP4C/Diamond-Manor-APrtentkitchen-4.jpg ',
    }
   
]

export default properties;
// https://i.ibb.co/dJyDTxD/penthouse-Kitchen-4.jpg